name: Allegiance
version: 1.0.0
main: net.arcation.allegiance.Allegiance
author: Mr_Little_Kitty
softdepend: [Citadel, NameLayer, Bastion]

commands:
   Allegiance:
      description: Base command for Allegiance
      usage: /Allegiance
      permission: Allegiance
      aliases: [al, alle]
