name: ${project.name}
version: ${project.version}
main: net.arcation.allegiance
author: Mr_Little_Kitty
depend: [Citadel, NameLayer]
commands:
   Allegiance:
      description: Base command for Allegiance
      usage: /Allegiance
      permission: Allegiance
permissions:
    Allegiance.*:
        description: Gives access to all Allegiance commands
        default: false
    Allegiance:
        description: idk something goes here
        default: false
