name: Allegiance
version: 1.0.0
main: net.arcation.allegiance.Allegiance
author: Mr_Little_Kitty
softdepend: [Citadel, Bastion, CombatTagPlus]

commands:
   Allegiance:
      description: Base command for Allegiance
      usage: /Allegiance
      permission: Allegiance
permissions:
    Allegiance.*:
        description: Gives access to all Allegiance commands
        default: false
    Allegiance:
        description: idk something goes here
        default: false
